---
title: 'Lab 5: Data wrangling and graphing COVID-19 reporting data (Part 2)'
author: "Abigail Gray"
date: "September 27, 2020"
output: html_document
---
### Exercises

* 2.

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```


```{r}
Confirmed_State_6_13 <- read_csv(url("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```


```{r}
str(Confirmed_State_6_13)
```


```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
Confirmed_State_9_13
```


```{r}
str(Confirmed_State_9_13)
```


```{r}
Confirmed_State_6_13 <- Confirmed_State_6_13 %>% 
  filter(Province_State != "Recovered")


Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered")
```


```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
```


```{r}
tail(Confirmed_State_6_13_9_13_joined, 5)
```
```{r}
which(is.na(Confirmed_State_6_13_9_13_joined))
```




```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y)

head(Confirmed_State_6_13_9_13_joined)
```


```{r}
Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
```


```{r, fig.width = 7, fig.height = 10}
ggplot(Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + 
    geom_point(aes(color = Date))
```
* 3.

```{r, fig.height = 10}
ggplot(Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + 
    geom_bar(stat = "identity", aes(fill = Date)) +
  labs(title = "Confirmed Covid-19 Cases in U.S.",
       x = "Confirmed Cases",
       y = "Province State" )
```


```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
view(time_series_confirmed)
```


```{r}
head(time_series_confirmed)
time_series_confirmed %>% filter(Country_Region == 'US')
```


```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 
```


```{r}
head(time_series_confirmed_long)
```


```{r}
 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
```


```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```


```{r}
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
```


```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```


```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
```


```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
```


```{r}
which(is.na(time_series_long_joined$Confirmed))
```


```{r}
which(is.na(time_series_long_joined$Deaths))
```


```{r}
library(lubridate)
```


```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```


```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```


```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
  ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```


```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South",
                                "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```


```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("China","France","Italy", 
                                "Korea, South", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
```


```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```


* 4.

```{r}
time_series_long_joined %>% 
    group_by(Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>%
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
```

* 5.

```{r}
time_series_joined_new_column <- time_series_long_joined %>%
  mutate(deaths_confirmed_ratio = Deaths / Confirmed)
head(time_series_joined_new_column)
```

* 6.

```{r}
time_series_joined_new_column <- time_series_long_joined %>%
  mutate(deaths_confirmed_ratio = Deaths / Confirmed) %>% 
  filter(Country_Region == "US")
time_series_joined_new_column %>%   
  ggplot(aes(x = Date, y = deaths_confirmed_ratio)) +
  geom_point() +
  geom_line() +
  labs(title = "US Covid-19 Deaths/Confirmed Cases", x = "Date", y = "Deaths/Confirmed")
```


* 7.

```{r}
time_series_top_deaths <- time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarize(Total_Deaths = max(Deaths)) %>% 
  arrange(desc(Total_Deaths)) %>% 
  slice(1:10)
time_series_top_deaths
```


```{r, y = 15}
time_series_long_joined %>%
  group_by(Date, Country_Region) %>% 
  summarise_at(c("Deaths"), sum) %>%
  filter(Country_Region %in% time_series_top_deaths$Country_Region) %>% 
  ggplot(aes(x = Date, y = Deaths, color = Country_Region)) +
  geom_point() +
  geom_line() +
  labs(title = "Highest Covid-19 Death Counts", x = "Date", y = "Total Deaths")
```


* 8.

```{r}
time_series_long_joined %>%
  group_by(Date, Country_Region) %>% 
  summarise_at(c("Deaths"), sum) %>%
  filter(Country_Region %in% time_series_top_deaths$Country_Region) %>% 
  ggplot(aes(x = Date, y = Deaths, color = Country_Region)) +
  geom_point() +
  geom_line() +
  facet_wrap(facets = vars(Country_Region), nrow = 2) +
  labs(title = "Highest Covid-19 Death Counts", x = "Date", y = "Total Deaths") 
```


* 9.

```{r}
time_series_US <-
read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"))
```
```{r}
time_series_US_long <- time_series_US %>%               
  pivot_longer(cols = 12:length(time_series_US),
                            names_to = "Date", values_to = "Confirmed") 
```

```{r message=FALSE, warning=FALSE, fig.height=30, fig.width=20}
time_series_US_long %>%
  filter (Country_Region == "US") %>% 
  group_by(Date, Province_State, Country_Region) %>% 
  summarise_at(c("Confirmed"), sum) %>%
  ggplot(aes(x = Date, y = Confirmed, color = Province_State)) +
  geom_point() +
  geom_line() +
  facet_wrap(facets = vars(Province_State), nrow = 25) +
  labs(title = "Highest Covid-19 Death Counts", x = "Date", y = "Total Deaths")
```

* 10

```{r}
time_series_long_joined %>%
  group_by(Date, Country_Region) %>% 
  summarise_at(c("Deaths"), sum) %>%
  filter(Country_Region %in% time_series_top_deaths$Country_Region) %>% 
  ggplot(aes(x = Date, y = Deaths, color = Country_Region)) +
  geom_point() +
  geom_line() +
  facet_wrap(facets = vars(Country_Region), nrow = 2) +
  labs(title = "Highest Covid-19 Death Counts", x = "Date", y = "Total Deaths") +
  theme_dark()
```












