---
title: 'Lab 6: Data Maps and Interactive Graphs from the COVID-19 reporting data'
author: "Abigail Gray"
date: "October 6, 2020"
output: html_document
bibliography: lab6_references.bib
---

Application written in R [@RCoreTeam]. Data retrieved from the JSU CSSE Covid-19 Data Repository [@CSSEGISandData_2020a]. Multiple tutorials were used for creating maps [@Andersen2018], [@pkdown], [@Moreno2018].

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
library(plotly)
```

### Exercise 1

```{r message=FALSE, warning=FALSE, include=FALSE}
daily_report <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Lat != "NA") %>% 
  filter(Long != "NA") %>% 
  group_by(Country_Region) %>%
  summarize(
            Lat = median(Lat),
            Long = median(Long),
            Confirmed = sum(Confirmed),
            Deaths = sum(Deaths))
```

```{r message=FALSE, warning=FALSE, include=FALSE}
world <- as_tibble(map_data("world"))
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(daily_report, aes(x = Long, y = Lat, size = Deaths/1000)) +
    borders("world", colour = NA, fill = "grey90") +
    theme_bw() +
    geom_point(shape = 21, color='purple', fill='purple', alpha = 0.5) +
    labs(title = 'World COVID-19 Deaths',x = '', y = '',
        size="Deaths (x1000))") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5)
```

### Exercise 2

```{r message=FALSE, warning=FALSE, include=FALSE}
daily_report <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Country_Region == "US") %>% 
  filter (!Province_State %in% c("Alaska","Hawaii", "American Samoa",
                  "Puerto Rico","Northern Mariana Islands", 
                  "Virgin Islands", "Recovered", "Guam", "Grand Princess",
                  "District of Columbia", "Diamond Princess")) %>% 
  filter(Lat > 0)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
mybreaks <- c(1, 100, 1000, 10000, 10000)
ggplot(daily_report, aes(x = Long, y = Lat, size = Confirmed)) +
    borders("state", colour = "white", fill = "grey90") +
    geom_point(aes(x=Long, y=Lat, size=Confirmed, color=Confirmed),stroke=F, alpha=0.7) +
    scale_size_continuous(name="Cases", trans="log", range=c(1,4), 
                        breaks=mybreaks, labels = c("1-99",
                        "100-999", "1,000-9,999", "10,000-99,999", "50,000+")) +
    scale_color_viridis_c(option="viridis",name="Cases",
                        trans="log", breaks=mybreaks, labels = c("1-99",
                        "100-999", "1,000-9,999", "10,000-99,999", "50,000+"))  +
  theme_void() + 
    guides( colour = guide_legend()) +
    labs(title = "Anisa Dhana's lagout for COVID-19 Confirmed Cases in the US'") +
    theme(
      legend.position = "bottom",
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#ffffff", color = NA), 
      panel.background = element_rect(fill = "#ffffff", color = NA), 
      legend.background = element_rect(fill = "#ffffff", color = NA)
    ) +
    coord_fixed(ratio=1.5)
```

### Exercise 3

```{r message=FALSE, warning=FALSE, include=FALSE}
library(RColorBrewer)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
report_09_26_2020 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  unite(Key, Admin2, Province_State, sep = ".") %>% 
  group_by(Key) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Key = tolower(Key))

us <- map_data("state")
counties <- map_data("county") %>% 
  unite(Key, subregion, region, sep = ".", remove = FALSE)

state_join <- left_join(counties, report_09_26_2020, by = c("Key"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  borders("state", colour = "black") +
  geom_polygon(data = state_join, aes(fill = Confirmed)) +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "OrRd"),
                       breaks = c(1, 10, 100, 1000, 10000, 100000),
                       trans = "log10", na.value = "White") +
  ggtitle("Number of Confirmed Cases by US County") +
  theme_bw() 
```

### Exercise 4

```{r message=FALSE, warning=FALSE, include=FALSE}
daily_report <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Province_State == "New Hampshire") %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))
us <- map_data("state")
nh_us <- subset(us, region == "new hampshire")
counties <- map_data("county")
nh_county <- subset(counties, region == "new hampshire")
state_join <- left_join(nh_county, daily_report, by = c("subregion" = "Admin2")) 
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
ggplotly(
  ggplot(data = nh_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(data = state_join, aes(fill = Confirmed), color = "white") +
    scale_fill_gradientn(colors = brewer.pal(n = 5, name = "YlOrRd")) +
  ggtitle("COVID-19 Cases in New Hampshire") +
  labs(x = "long", y= "lat") +
  theme_gray()
)
```

### REFERENCES