---
title: 'Lab 9A: Control Structures and Functions'
author: "Abigail Gray"
date: "11/16/2020"
output: html_document
---

### Conditional statements with if-else

```{r}
x <- runif(1, 0, 20)  
if(x > 10) {
        y <- 7
} else {
        y <- 3
}
```

### for Loops

```{r}
for(i in 3:12) {
        print(i)
}
```

```{r}
fruits <- c("apple", "banana", "pear")
for(i in 1:3) {
        ## Print out each element of 'x'
        print(x[i])  
}
```

```{r}
for(i in seq_along(fruits)) {   
        print(fruits[i])
}
```

```{r}
for(letter in fruits) {
        print(letter)
}
```

```{r}
for(i in 1:3) print(fruits[i])
```

### Nested for loops

```{r}
x <- matrix(1:8, 2, 4)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
```

### while Loops

```{r}
count <- 0
while(count < 20) {
        print(count)
        count <- count + 2
}
```

```{r}
z <- 5
set.seed(1)
while(z >= 2 && z <= 9) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {  ## random walk
                z <- z + 3
        } else {
                z <- z - 3
        } 
}
print(z)
```

### Functions

```{r}
f <- function() {
  
}

class(f)
```

```{r}
f()
```

```{r}
f <- function() {
        cat("Bananas!\n")
}
f()
```

```{r}
f <- function(num) {
        for(i in seq_len(num)) {
                cat("Bananas!\n")
        }
}
f(6)
```

```{r}
f <- function(num) {
        hello <- "Bananas!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
meaningoflife <- f(2)
```

```{r}
print(meaningoflife)
```

```{r}
f <- function(num = 2) {
        hello <- "Bananas!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
f()
```

```{r}
f(4)
```

```{r}
f(num = 1)
```







